# Deploying on k8s
apiVersion: v1
kind: Service
metadata:
  name: envoy-authz
  labels:
    app: envoy-authz
spec:
  ports:
  - name: grpc
    port: 9000
    targetPort: 9000
  selector:
    app: envoy-authz
---
# Injecting casbin admission to Istio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-authz
  template:
    metadata:
      labels:
        app: envoy-authz
    spec:
      containers:
      - image: casbin/envoy-authz:1.0
        imagePullPolicy: IfNotPresent
        name: envoy-authz
        ports:
        - containerPort: 9000
---
  